### ISSUE TITLE
Investigate real-time availability indexing in Alma

### ISSUE THREAD

**Issue by kelynch** [pulibrary/marc_liberation#629]
Investigate the ability to retrieve real-time availability information for a given set of bib records, holdings, or items, abstracted into the existing API in `marc_liberation`.

**Comment by christinach** [comment]
- [ ] Indexing availability information from the **daily** incremental dumps from Alma. Set up a publishing job. https://github.com/pulibrary/marc_liberation/issues/651
- [ ] Real time on search results and the record display and the requests page. https://github.com/pulibrary/marc_liberation/issues/641
- [ ] Full reindex. Make sure this ad hoc job of a full dump would include the availability. https://github.com/pulibrary/marc_liberation/issues/649
- [ ] Ask exlibris how often we can have a full dump. https://github.com/pulibrary/marc_liberation/issues/650

**Comment by hackmastera** [comment]
@mzelesky will get a list of all the "summary availability" values Alma returns. To get more detailed availability values, one has to query the bib for all the holdings ids, loop through each of those to get the item ids, and then retrieve each item to get its specific status.

**Comment by hackmastera** [comment]
We found the list. The options are: "Available", "Unavailable", and "Check Holdings"

see https://knowledge.exlibrisgroup.com/Primo/Product_Documentation/Primo/Technical_Guide/160Mapping_to_the_Normalized_Record/030Alma_MARC_21#Availability_Statuses_from_Alma

**Comment by kelynch** [comment]
This has been sufficiently investigated.
