### ISSUE TITLE
Update traject to process Alma records

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/marc_liberation#806]
Alma records place fields merged from items in a different location in the record than Voyager did. The fields in question are recorded in ADRS: https://github.com/pulibrary/marc_liberation/tree/master/architecture_decisions. The publishing profile is documented at https://docs.google.com/spreadsheets/d/1xWA7lmICLp5sT2yROPyeKz_AbOsBa_nNhjNCDGDE2O8/edit#gid=0 

Comments have been left inline in [traject_config.rb](https://github.com/pulibrary/marc_liberation/blob/a691bf10e8f475172a586921d003f8f280329589/marc_to_solr/lib/traject_config.rb)

The configurations that are needed:
- [x] catalog date #926
- [x] locations #823
- [x] electronic access fields #921 
- [x] contained in #922
- [x] call_number_display #923
- [x] call_number_browse_s  #947
